spring:
  datasource:
    url: jdbc:mysql://svc.sel4.cloudtype.app:30996/tera_blog
    username: terauser
    password: tera1234!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
